server:
  port: 8093
spring:
  profiles:
    include: jpa, mybatis, flyway,redis
  application:
    name: customer-service
  flyway:
    placeholders: {table_space: TBLBATCH_TASK, db_script_i18n: en}
mybatis-plus:
  type-enums-package: com.sa.customer.dto.job
  type-handlers-package: com.sa.customer.handle
logging:
  level:
    com.sa: debug