server:
  port: 8090
spring:
  application:
    name: product-service
  datasource:
    username: SA_DB
    password: xujin
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.20.56:1521/ORACLEPDB
    type: com.alibaba.druid.pool.DruidDataSource
    # 此处需要使用配置文件将配置注入
    initialSize: 5 # 初始化数量
    maxActive: 20 # 最大活动连接数
    minIdle: 1 # 最小空闲数量
    maxWait: 6000 # 最大等待时间
  jpa:
    #配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
#    hibernate:
#      #配置指明在程序启动的时候要删除并且创建实体类对应的表
#      ddl-auto: update

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
  type-enums-package:  com.sa.common.dto.job
  type-handlers-package: com.sa.product.handle
#feign:
#  okhttp:
#    enabled: true
#  httpclient:
#    maxConnections: 200
#    maxConnectionsPerRoute: 50
#    connectionTimeout: 60000
#    connectionTimerRepeat: 70000
#  client:
#    config:
#      default:
#        connectTimeout: 60000
#        readTimeout: 60000
#        loggerLevel: basic
#        contract: feign.jaxrs.JAXRSContract

logging:
  level:
    com.sa: debug