server:
  port: 8090
spring:
  profiles:
    include: jpa, mybatis, flyway
  application:
    name: product-service
mybatis-plus:
  type-enums-package:  com.sa.common.dto.job
  type-handlers-package: com.sa.product.handle
logging:
  level:
    com.sa: debug