CREATE TABLE BATCH_TASK
(
    TASK_ID     NUMBER(15),
    TYPE        NUMBER(2),
    DATA        VARCHAR(4000),
    STATE       NUMBER(3),
    TOTAL       NUMBER(10),
    SUCCESS_NUM NUMBER(10) DEFAULT 0,
    FAIL_NUM    NUMBER(10) DEFAULT 0,
    TASK_LEVEL  NUMBER(3)
);