server:
  port: 20001
spring:
  application:
    name: sa-login
  datasource:
    username: SA_DB
    password: xujin
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1721:xe
mybatis:
  mapper-locations: classpath:mapping/*.xml

# feign : FeignClientProperties
feign:
  okhttp:
    enabled: true
  httpclient:
    maxConnections: 200
    maxConnectionsPerRoute: 50
    connectionTimeout: 60000
    connectionTimerRepeat: 70000
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
        contract: feign.jaxrs.JAXRSContract

